### ISSUE TITLE
Delete twitter/X-link from Startseite

### ISSUE THREAD

**Issue by aseipelt** [Edirom/ess-website#126]
Do we still need the twitter/X-link on the website? I suggest to delete it. 

--> footer.html

**Comment by riedde** [comment]
Thanks @aseipelt for spotting! I haven't been in that corner of the Homepage for a long time.
We decided to remove twitter-links form the website (see https://github.com/Edirom/ess-website/blob/b5c813fa0cf116f34bfd7e17f72750c5e954bb5e/_posts/2023-11-06-twitter-feature-deleted.md?plain=1#L4). I guess that this is a relict. So I you like, you can delete it.

**Comment by peterstadler** [comment]
will remove the icon with @aseipelt
