### ISSUE TITLE
improve program list group for small screens

### ISSUE THREAD

**Issue by peterstadler** [Edirom/ess-website#83]
see e.g. iPhone size
![Bildschirmfoto 2021-03-01 um 08 52 28](https://user-images.githubusercontent.com/2247936/109467437-76505e80-7a6b-11eb-95aa-d63ff0f6762d.png)

**Comment by bwbohl** [comment]
evtl. so wie bei der MEI oder den music encoding conferences? siehe music-encoding.org

**Comment by peterstadler** [comment]
@bwbohl hmm, welche Seite bei music-encoding.org hat so eine Listen-Navigation auf der linken Seite?

**Comment by bwbohl** [comment]
erstmal nicht links aber auf kleinen Bildschirmen: https://music-encoding.org/conference/2021/

**Comment by peterstadler** [comment]
Ja, das ist eine gute Lösung! Wobei ich es in dem konkreten Beispiel nicht ideal finde, dass sich die beiden Hamburger (von der Top-Navigation und der untergeordneten Seitennavigation) doppeln. Vielleicht könnte man aber eine horizontale sekundäre Navigationsleiste einziehen für kleine Displays. Ich schaue mir das mal an …
