### ISSUE TITLE
reduce footer height for small screens

### ISSUE THREAD

**Issue by peterstadler** [Edirom/ess-website#84]
![Bildschirmfoto 2021-03-01 um 08 54 06](https://user-images.githubusercontent.com/2247936/109467583-b0b9fb80-7a6b-11eb-8158-f722868dd6d0.png)

**Comment by bwbohl** [comment]
potentially also improve log placement in footer for small screens?

**Comment by riedde** [comment]
On my mobile (IPhone SE) there is just a small or none footer without content. The other parts of the page seem to be responsive.

**Comment by riedde** [comment]
Checked again also with tablet. When the screen is to small the footer disapears. The rest of the page seems to be responsive in all cases.
